import pandas as pd

df = pd.DataFrame(
    {
        "Indicador": [
            "Detalhes organizacionais",
            "Período e frequência de elaboração de relatório",
            "Atividades, cadeia de valor e outras relações de negócios",
            "Total de colaboradores no CESAR / Julho 2022",
            "Governança, estrutura e composição",
            "Presidente do Conselho",
            "Papel do presidente do Conselho em supervisionar a gestão de impacto",
            "Delegação de responsabilidade da gestão de impactos",
            "Papel do presidente do Conselho em supervisionar a gestão de impacto",
            "Comunicação de questões-chave",
            "Conhecimento coletivo do mais alto nível de governança",
            "Declaração de estratégia de desenvolvimento sustentável",
            "Processos para remediar impactos negativos",
            "Abordagem para engajamento das partes interessadas",
            "Quantidade de empresas do Porto Digital",
            "Pessoas empregadas no Porto Digital",
            "Faturamento do Porto Digital",
            "Projetos Executados por ano",
            "Nota do GlassDoor",
            "Recomendam o CESAR para um amigo",
            "Tem uma Perspectiva positiva do CESAR",
            "Índice Sistema B",
            "Ebitda",
        ],
        
         "Unidade": [
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "1.234",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "qualitativo / descritivo",
            "350+",
            "15.000+",
            "3,67bi",
            "140+",
            "4,8",
            "98%",
            "92%",
            "100.2",
            "R$ 16.635.560,00",
         ],

         # "Escopo": [
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "janeiro a setembro de 2022",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         # ],

         # "GRI Standard Disclosure": [
         #    "2-1 Organizational details",
         #    "2-3 Reporting period, frequency and contact point",
         #    "2-6 Activities, value chain and other business relationships",
         #    "2-7 Employees",
         #    "2-11 Chair of the highest governance body",
         #    "2-9 Governance structure and composition",
         #    "2-12 Role of the highest governance body in overseeing the management of impacts",
         #    "2-13 Delegation of responsibility for managing impacts",
         #    "2-14 Role of the highest governance body in sustainability reporting",
         #    "2-16 Communication of critical concerns",
         #    "2-17 Collective knowledge of the highest governance body",
         #    "2-22 Statement on sustainable development strategy",
         #    "2-25 Processes to remediate negative impacts",
         #    "2-29 Approach to stakeholder engagement",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
             
         # ],

         #  "ODS": [
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "",
         #    "8,8",
         #    "",
         #    "",
         #    "8,8",
         #    "8,8",
         #    "8,8",
         #    "",
         #    "8,8",
         #  ],
    }
)

df.to_csv("dados_adm.csv", index=False)