import pandas as pd

df = pd.DataFrame(
    {
        "Indicador": [
            "Colaboradores LGBTQIA+",
            "Colaboradores negros",
            "Colaboradoras mulheres",
            "Idade Média dos Colaboradores",
            "Colaboradores com deficiência",
            "Colaboradores que fazem parte de algum grupo minorizado",
            "Mulheres na Liderança técnica",
            "Mulheres na Média Liderança",
            "Mulheres na Alta Liderança",
            "Pessoas Negras na Liderança Técnica",
            "Pessoas Negras na Média Liderança",
            "Pessoas Negras na Alta Liderança",
            "Total de colaboradores no CESAR / Julho 2022",
            "Total de Estagiários",
            "PCDs",
            "Pessoas pardas",
            "Pessoas pretas",
            "Mulheres",
            "50+",
            "e-NPS",
            "Turnover Geral até Julho 2022",
            "Índice de Recrutamento interno de 2022 até Julho",
            "Vagas Destinadas a Recrutamento Interno",
        ],

        "Unidade": [
            "16%",
            "34%",
            "37%",
            "33 anos",
            "7%",
            "66%",
            "26%",
            "61%",
            "56%",
            "32%",
            "29%",
            "24%",
            "1.234",
            "90",
            "2%",
            "30%",
            "5%",
            "32%",
            "5%",
            "91,30%",
            "7,26%",
            "17%",
            "5%",
        ],
        
        "Escopo": [
            "",
            "",
            "",
            "",
            "Data de resposta: 06-07/2021",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Janeiro a julho de 2022",
            "",
            "",
            "",
            "Janeiro a julho de 2022",
            "",
            "",
            "",
            "",
            "",
         ],

         "GRI Standard Disclosure": [
            "",
            "",
            "",
            "",
            "405-1 Diversity of governance bodies",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2-7",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "401-1 New employee hires and employee turnover",
            "",
            "",
        ],

        "ODS": [
            "10, 2",
            "5,5",
            "10, 2",
            "10, 2",
            "10, 2",
            "5,5",
            "5,5",
            "5,5",
            "10, 2",
            "10, 2",
            "10, 2",
            "12, 2",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "8,8",
            "8,8",
            "8,8",
        ],

    }
)